<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use App\Helpers\Qs;
use Illuminate\Support\Str;

class CuaHangTableSeeder extends Seeder
{

    /**
     * Run the database seeds.
     *
     * @return void
     */
    // 
 
    public function run()
    {
        $cuahangs = ["GAP","NIKE","ESTELLE","YVES ROCHER","LOTTERIA","PEPPER LUNCH","KFC","COUPLE TX","THE BLUES - CHILDREN SMILE","MAT VIET","URAETEI BBQ RESTAURANT","KING BBQ","OGAWA","MEDICARE","DREAM GAMES","LEVIS","VALENTINO CREATIONS","MIKI","BELLUNI","MARUKAME UDON","TINIWORLD","MY KINGDOM","BANGKOK HOUSE","THE FACE SHOP","HOTPOT STORY & KHAO LAO","CGV","ILA","ROHTO","DAISO","SAMSONITE","THE BODY SHOP","FAHASA","KOMONOYA","MARC","BREADTALK","ADIDAS","KICHI KICHI","CONVERSE","HOANG PHUC","GOGI HOUSE","VANS","NINOMAXX","MEGANE PRINCE","IBASIC","AOKANG","NEWBALANCE AND CROCS","PNJ","BAMBOO DIMSUM","MINIGOOD","MON VIET","OHI PERFUME","CHANG KANG KUNG & A DOI","PIZZA HUT","RELAX N GO","OKARA","CHICHIKO","VIET DELI","HAI SAN CUA","COM NGON AND LAU CONG CHUA","UMBRELLA","LEMINO","OWEN","AN PHUOC","BEAUTY BOX","ALDO","HIGHLANDS COFFEE","TEXAS CHICKEN","COLOR BOX","PAPAXOT","MC DONALD'S","BOBAPOP","MON HAN","ICE POP POP","FITFLOP","MAXXKER","MANGO","TOMMY JEANS","BEVERY HILLS POLO CLUB","PARFOIS","KOHNAN","OWNDAYS","HLA","INNISFREE","OVS","LINING","LIME ORANGE","MAXXSPORT","SKECHERS","REEBOK","CANIFA","THE SCENT","JANG IN","RABITY","BB WELLNESS","OKIA","LUG.VN - ECHOLAC","FOODEE RESTOP","FANPEKKA","KOI THE","DECATHLON","KUMON","AKEMI UCHI","MOLLY FANTASY","SUKIYA","JELLY BUNNY","LOCK N LOCK","ANTA","LYN","ARIZE","JYSK","MOTHER CARE","USHI MANIA","H&M","R N B","FANCY TIME","ASICS","YAMAHA","CON CUNG","AL FRESCOS","AEON BIKE","WELLNESS","TRONG COM-CHAO CA-HOANG YEN HOTPOT","HOANG YEN BUFFET","HUROM JUICE CAFÉ","SUSHI KEI","MEIWEI","AEON PET (PETEMO)","Aeon GARDEN","THE PIZZA COMPANY","MK RESTAURANT","GYU KAKU","CRYSTAL JADE","HUTONG","MOMOTAROU","POSH","OPPO","TIMEZONE","CALIFORNIA FITNESS & YOGA","THAI EXPRESS","HOKKAIDO","DOOKKI","FRICO LIFESTYLE CENT","JOCKEY","MY WISH","TOP ART","GOJOY.VN","20 AGAIN","GUMAC","LANGFARM","MAY10","MAGIC PHOTO","TUTU TRAIN","GIORDANO","DREAM KIDS","LAU BA DUA","KYMDAN","LE MONDE STEAK","STYLE BY PNJ","BJ  TOKBOKKI","MILENSEA","U AND YABY","VP PHOTOBOOTH","GABBY","CHARLES&KEITH","PEDRO","BALA BALA","LIZD NAMAT","LOVEKIDS","PIZZA 4PS","JIANGHU HEROES HOTPO","DAI THANH FENG SHUI","TVWORLD","WESTWAYS","THAI NGON NGON","BONCHON","DONG HAI","STARBUCKS","DAIRY QUEEN","OLV","INOCHI","BOO","POT AND FOOD","NSHOP","MINISO","CLEVER BOX","DIGIBOX","WUNDERTUTE","ROUTINE","TIMEZONE-S72","KPUB","MANWAH","ISUSHI","LOC PHUC","KATINAT","DYSON","HOA DELI","QUICHES","LIFE 4 CUTS","SAMSUNG","HIMALAYA","UNIQLO","DEP ACCESSORIES","SASANA","LUBIT","KIM GOON SOCKS","OP WORLD",];
    
        DB::table('cuahangs')->delete();

        $d = [ ];
        foreach($cuahangs as $cuahang) {
            $data = ['name' => $cuahang];
            array_push($d, $data);
        }  
        DB::table('cuahangs')->insert($d);
    }

}
